### ISSUE TITLE
question about re-training EDM

### ISSUE THREAD

**Issue by forever208** [giannisdaras/cdm#3]
Hi, thanks for your awesome work and the open-source code.

I have a question, in your paper, you said "we refer to the models trained with vanilla Denoising Score Matching (DSM) as “EDM” models". Did you re-train EDM-VP without using their preconditioning loss (i.e. their eq. (8) in their paper)?

**Comment by giannisdaras** [comment]
Hey! Thanks a lot for your question.
No, the "vanilla DSM" refers to the fact that these models were trained without consistency regularization. They are still trained with the preconditioning from the EDM paper.

**Comment by forever208** [comment]
Thanks a lot for the reply!
